class QuotesRepository {
  static const List<String> quotes = [
    "No importa cuán lento vayas, siempre y cuando no te detengas.",
    "La ansiedad de anticipación siempre es peor que la realidad del momento.",
    "Las palabras amables pueden ser cortas y fáciles de decir, pero sus ecos son infinitos.",
    "Para ser interesante, sé interesado. Escuchar es el 50% de la buena comunicación.",
    "La disciplina es elegir entre lo que quieres ahora y lo que quieres más.",
    "Acepta lo que es, deja ir lo que fue, ten fe en lo que será.",
    "El crecimiento comienza donde termina tu zona de confort.",
    "No te preocupes por equivocarte; preocúpate por las oportunidades que pierdes al no intentarlo.",
    "La verdadera libertad es no tener que depender de la aprobación externa.",
    "Respira hondo. Estás seguro, estás preparado, eres capaz.",
    "El silencio también es una forma de comunicación asertiva.",
    "Nadie recuerda tus errores tanto como tú. Relájate.",
    "La timidez es un escudo que ya no necesitas llevar.",
    "Tus ideas tienen valor. Permíteles ver la luz.",
    "El autocontrol es la mayor de las fortalezas.",
    "La paz interior empieza en el momento en que eliges no permitir que otra persona o evento controle tus emociones.",
    "Cada oportunidad para hablar es un regalo para compartir, no una prueba para pasar.",
    "La tranquilidad mental rompe las barreras de expresar tus ideas con claridad.",
    "El amor propio te guía hacia transformar los nervios en energía.",
    "La resiliencia se nutre al encontrar tu centro de paz.",
    "El crecimiento personal significa poder respirar hondo antes de actuar.",
    "Hablar en público se nutre al expresar tus ideas con claridad.",
    "La perseverancia te enseña a proyectar seguridad al hablar.",
    "La paciencia te protege de transformar los nervios en energía.",
    "El amor propio se basa en ignorar las opiniones destructivas.",
    "La valentía es fundamental para aprender de cada error.",
    "El autoconocimiento nos permite dar un paso adelante cada día.",
    "El coraje se nutre al proyectar seguridad al hablar.",
    "El coraje se logra al reconocer tu propio valor.",
    "Tu voz es la clave para reconocer tu propio valor.",
    "El desarrollo propio se fortalece al expresar tus ideas con claridad.",
    "El enfoque te protege de reconocer tu propio valor.",
    "El enfoque te da la fuerza para avanzar sin importar los obstáculos.",
    "La calma te impulsa a encontrar tu centro de paz.",
    "La armonía se basa en mantener la mente enfocada.",
    "El esfuerzo consiste en avanzar sin importar los obstáculos.",
    "La atención plena te protege de aprender de cada error.",
    "El enfoque te enseña a proyectar seguridad al hablar.",
    "El enfoque es el primer paso para dar un paso adelante cada día.",
    "El pensamiento positivo comienza cuando decides cultivar una mente en calma.",
    "El equilibrio te impulsa a encontrar tu centro de paz.",
    "El enfoque abre la puerta a superar la necesidad de aprobación.",
    "Superar la timidez te da la fuerza para construir hábitos inquebrantables.",
    "Vencer los nervios consiste en cultivar una mente en calma.",
    "El autocontrol te conecta con soltar lo que no puedes controlar.",
    "La sabiduría consiste en abrazar tu verdadera esencia.",
    "La paz interior se nutre al expresar tus ideas con claridad.",
    "El equilibrio es la clave para proyectar seguridad al hablar.",
    "La resiliencia comienza cuando decides avanzar sin importar los obstáculos.",
    "El desarrollo propio construye el camino para vivir el momento presente.",
    "El miedo al rechazo te enseña a construir hábitos inquebrantables.",
    "La fuerza de voluntad te da la fuerza para disfrutar del proceso de crecimiento.",
    "La verdadera disciplina te da la fuerza para dejar atrás la ansiedad social.",
    "La calma consiste en superar la necesidad de aprobación.",
    "Tu voz te enseña a aprender de cada error.",
    "La tranquilidad mental se fortalece al creer en el poder de tus palabras.",
    "La constancia comienza cuando decides soltar lo que no puedes controlar.",
    "El budismo nos enseña que requiere que aprendas a transformar los nervios en energía.",
    "La valentía te protege de superar la necesidad de aprobación.",
    "La motivación consiste en cultivar una mente en calma.",
    "La fuerza de voluntad rompe las barreras de enfrentar tus miedos.",
    "La paz interior te protege de enfrentar tus miedos.",
    "La resiliencia comienza cuando decides disfrutar del proceso de crecimiento.",
    "El autoconocimiento se logra al confiar en tus capacidades.",
    "La verdadera disciplina te enseña a proyectar seguridad al hablar.",
    "La sabiduría transforma tu manera de avanzar sin importar los obstáculos.",
    "El miedo al rechazo nace de la capacidad de comunicar lo que sientes.",
    "La asertividad requiere que aprendas a reconocer tu propio valor.",
    "El crecimiento personal se basa en expresar tus ideas con claridad.",
    "La perseverancia requiere que aprendas a reconocer tu propio valor.",
    "La calma te enseña a vivir el momento presente.",
    "El amor propio se nutre al creer en el poder de tus palabras.",
    "El pensamiento positivo te enseña a conectar auténticamente con los demás.",
    "El miedo al rechazo requiere que aprendas a construir hábitos inquebrantables.",
    "El budismo nos enseña que ilumina el sendero hacia transformar los nervios en energía.",
    "La calma nace de la capacidad de avanzar sin importar los obstáculos.",
    "La calma consiste en construir hábitos inquebrantables.",
    "La asertividad te da la fuerza para construir hábitos inquebrantables.",
    "El equilibrio se basa en expresar tus ideas con claridad.",
    "El pensamiento positivo se fortalece al enfrentar tus miedos.",
    "El enfoque consiste en aprender de cada error.",
    "La valentía te guía hacia enfrentar tus miedos.",
    "Hablar en público construye el camino para comunicar lo que sientes.",
    "Tu confianza te ayuda a comunicar lo que sientes.",
    "La fuerza de voluntad se nutre al dar un paso adelante cada día.",
    "La atención plena te enseña a mantener la mente enfocada.",
    "El esfuerzo es la clave para mantenerse firme ante la adversidad.",
    "La constancia se basa en abrazar tu verdadera esencia.",
    "La motivación nos permite disfrutar del proceso de crecimiento.",
    "Superar la timidez te protege de disfrutar del proceso de crecimiento.",
    "La armonía abre la puerta a dejar atrás la ansiedad social.",
    "La atención plena es la clave para mantener la mente enfocada.",
    "El desarrollo propio te guía hacia dar un paso adelante cada día.",
    "Tu confianza es el reflejo de confiar en tus capacidades.",
    "El coraje te da la fuerza para transformar los nervios en energía.",
    "El budismo nos enseña que es el arte de aprender de cada error.",
    "Tu confianza consiste en superar la necesidad de aprobación.",
    "El desarrollo propio es el arte de dejar atrás la ansiedad social.",
    "La fuerza de voluntad te guía hacia expresar tus ideas con claridad.",
    "La calma significa poder superar la necesidad de aprobación.",
    "Tu voz abre la puerta a mantenerse firme ante la adversidad.",
    "Vencer los nervios comienza cuando decides confiar en tus capacidades.",
    "La verdadera disciplina te protege de abrazar tu verdadera esencia.",
    "La serenidad te guía hacia mantener la mente enfocada.",
    "La determinación te libera de disfrutar del proceso de crecimiento.",
    "La paz interior te conecta con construir hábitos inquebrantables.",
    "El equilibrio nos permite dejar atrás la ansiedad social.",
    "La atención plena te impulsa a aprender de cada error.",
    "Hablar en público es el arte de disfrutar del proceso de crecimiento.",
    "La verdadera disciplina te protege de creer en el poder de tus palabras.",
    "Tu confianza se nutre al soltar lo que no puedes controlar.",
    "El autoconocimiento es el reflejo de superar la necesidad de aprobación.",
    "El esfuerzo comienza cuando decides confiar en tus capacidades.",
    "Hablar en público se nutre al aprender de cada error.",
    "La armonía construye el camino para cultivar una mente en calma.",
    "El miedo al rechazo te protege de cultivar una mente en calma.",
    "El equilibrio es el reflejo de conectar auténticamente con los demás.",
    "La calma te conecta con vivir el momento presente.",
    "La atención plena te conecta con expresar tus ideas con claridad.",
    "La atención plena te protege de creer en el poder de tus palabras.",
    "La constancia consiste en ignorar las opiniones destructivas.",
    "La asertividad te impulsa a confiar en tus capacidades.",
    "El autoconocimiento abre la puerta a enfrentar tus miedos.",
    "La asertividad transforma tu manera de aprender de cada error.",
    "El autocontrol construye el camino para creer en el poder de tus palabras.",
    "El desarrollo propio ilumina el sendero hacia construir hábitos inquebrantables.",
    "El autoconocimiento te ayuda a disfrutar del proceso de crecimiento.",
    "El equilibrio es la clave para soltar lo que no puedes controlar.",
    "La verdadera disciplina te ayuda a encontrar tu centro de paz.",
    "El budismo nos enseña que te protege de dar un paso adelante cada día.",
    "Hablar en público comienza cuando decides superar la necesidad de aprobación.",
    "Hablar en público transforma tu manera de encontrar tu centro de paz.",
    "El amor propio abre la puerta a cultivar una mente en calma.",
    "La tranquilidad mental comienza cuando decides proyectar seguridad al hablar.",
    "La perseverancia se logra al respirar hondo antes de actuar.",
    "El autoconocimiento se logra al enfrentar tus miedos.",
    "La asertividad es el primer paso para vivir el momento presente.",
    "La resiliencia es el primer paso para dejar atrás la ansiedad social.",
    "Vencer los nervios te impulsa a conectar auténticamente con los demás.",
    "El equilibrio consiste en encontrar tu centro de paz.",
    "La asertividad transforma tu manera de mantenerse firme ante la adversidad.",
    "La perseverancia ilumina el sendero hacia proyectar seguridad al hablar.",
    "La sabiduría nace de la capacidad de dejar atrás la ansiedad social.",
    "El budismo nos enseña que te conecta con abrazar tu verdadera esencia.",
    "La valentía abre la puerta a superar la necesidad de aprobación.",
    "El miedo al rechazo te guía hacia comunicar lo que sientes.",
    "El autocontrol construye el camino para mantener la mente enfocada.",
    "El equilibrio nos permite avanzar sin importar los obstáculos.",
    "La determinación es el primer paso para transformar los nervios en energía.",
    "La verdadera disciplina ilumina el sendero hacia proyectar seguridad al hablar.",
    "Tu confianza requiere que aprendas a proyectar seguridad al hablar.",
    "La sabiduría es el primer paso para abrazar tu verdadera esencia.",
    "Tu voz rompe las barreras de confiar en tus capacidades.",
    "El equilibrio te conecta con proyectar seguridad al hablar.",
    "La tranquilidad mental requiere que aprendas a mantenerse firme ante la adversidad.",
    "La serenidad transforma tu manera de superar la necesidad de aprobación.",
    "La atención plena es el primer paso para comunicar lo que sientes.",
    "El pensamiento positivo nace de la capacidad de respirar hondo antes de actuar.",
    "La motivación te enseña a aprender de cada error.",
    "Tu voz te enseña a mantenerse firme ante la adversidad.",
    "La perseverancia es el arte de proyectar seguridad al hablar.",
    "El miedo al rechazo es el reflejo de expresar tus ideas con claridad.",
    "La constancia se basa en ignorar las opiniones destructivas.",
    "El autoconocimiento rompe las barreras de expresar tus ideas con claridad.",
    "Hablar en público es el arte de abrazar tu verdadera esencia.",
    "El autoconocimiento se fortalece al creer en el poder de tus palabras.",
    "El coraje construye el camino para encontrar tu centro de paz.",
    "La paciencia es la clave para confiar en tus capacidades.",
    "Tu confianza se fortalece al encontrar tu centro de paz.",
    "Superar la timidez nace de la capacidad de transformar los nervios en energía.",
    "La serenidad es fundamental para soltar lo que no puedes controlar.",
    "El pensamiento positivo te ayuda a reconocer tu propio valor.",
    "El esfuerzo requiere que aprendas a creer en el poder de tus palabras.",
    "El coraje requiere que aprendas a comunicar lo que sientes.",
    "El coraje se nutre al aprender de cada error.",
    "La paciencia te ayuda a creer en el poder de tus palabras.",
    "La serenidad se basa en conectar auténticamente con los demás.",
    "El pensamiento positivo ilumina el sendero hacia construir hábitos inquebrantables.",
    "La paz interior ilumina el sendero hacia superar la necesidad de aprobación.",
    "El pensamiento positivo es fundamental para transformar los nervios en energía.",
    "La perseverancia te libera de avanzar sin importar los obstáculos.",
    "Vencer los nervios se nutre al avanzar sin importar los obstáculos.",
    "La paciencia te libera de dejar atrás la ansiedad social.",
    "El autocontrol te protege de conectar auténticamente con los demás.",
    "La paz interior te impulsa a dar un paso adelante cada día.",
    "El éxito diario ilumina el sendero hacia vivir el momento presente.",
    "La perseverancia rompe las barreras de enfrentar tus miedos.",
    "El enfoque es el primer paso para enfrentar tus miedos.",
    "El desarrollo propio te guía hacia cultivar una mente en calma.",
    "El esfuerzo te protege de ignorar las opiniones destructivas.",
    "El equilibrio construye el camino para dejar atrás la ansiedad social.",
    "La atención plena nace de la capacidad de soltar lo que no puedes controlar.",
    "La perseverancia es el primer paso para enfrentar tus miedos.",
    "La atención plena se fortalece al enfrentar tus miedos.",
    "Tu confianza es fundamental para comunicar lo que sientes.",
    "El miedo al rechazo te protege de encontrar tu centro de paz.",
    "La calma es el arte de comunicar lo que sientes.",
    "Tu voz transforma tu manera de construir hábitos inquebrantables.",
    "La determinación se nutre al proyectar seguridad al hablar.",
    "El miedo al rechazo significa poder mantenerse firme ante la adversidad.",
    "El enfoque transforma tu manera de ignorar las opiniones destructivas.",
    "La calma ilumina el sendero hacia confiar en tus capacidades.",
    "La calma se logra al mantenerse firme ante la adversidad.",
    "Tu confianza te conecta con comunicar lo que sientes.",
    "La armonía te enseña a vivir el momento presente.",
    "La resiliencia te guía hacia aprender de cada error.",
    "La paz interior te impulsa a transformar los nervios en energía.",
    "La calma te protege de superar la necesidad de aprobación.",
    "El equilibrio transforma tu manera de encontrar tu centro de paz.",
    "El miedo al rechazo te ayuda a mantenerse firme ante la adversidad.",
    "La calma transforma tu manera de abrazar tu verdadera esencia.",
    "El budismo nos enseña que te protege de confiar en tus capacidades.",
    "El equilibrio te ayuda a confiar en tus capacidades.",
    "La paciencia se nutre al dejar atrás la ansiedad social.",
    "El esfuerzo se logra al expresar tus ideas con claridad.",
    "La tranquilidad mental te libera de reconocer tu propio valor.",
    "El miedo al rechazo te libera de dar un paso adelante cada día.",
    "La motivación rompe las barreras de creer en el poder de tus palabras.",
    "La valentía se basa en dejar atrás la ansiedad social.",
    "Tu voz construye el camino para dejar atrás la ansiedad social.",
    "El crecimiento personal se nutre al proyectar seguridad al hablar.",
    "El pensamiento positivo es el arte de enfrentar tus miedos.",
    "La tranquilidad mental te impulsa a encontrar tu centro de paz.",
    "La perseverancia te protege de mantener la mente enfocada.",
    "La constancia es la clave para abrazar tu verdadera esencia.",
    "La valentía consiste en construir hábitos inquebrantables.",
    "La perseverancia abre la puerta a confiar en tus capacidades.",
    "La determinación es fundamental para vivir el momento presente.",
    "El pensamiento positivo es el primer paso para dejar atrás la ansiedad social.",
    "El enfoque se logra al conectar auténticamente con los demás.",
    "El enfoque te guía hacia enfrentar tus miedos.",
    "La fuerza de voluntad te guía hacia proyectar seguridad al hablar.",
    "La armonía se basa en dar un paso adelante cada día.",
    "La fuerza de voluntad es la clave para transformar los nervios en energía.",
    "Hablar en público te enseña a construir hábitos inquebrantables.",
    "El autoconocimiento te conecta con construir hábitos inquebrantables.",
    "Vencer los nervios es la clave para mantener la mente enfocada.",
    "Tu confianza te guía hacia conectar auténticamente con los demás.",
    "Tu voz consiste en disfrutar del proceso de crecimiento.",
    "La fuerza de voluntad se logra al respirar hondo antes de actuar.",
    "El amor propio es el reflejo de superar la necesidad de aprobación.",
    "El crecimiento personal es fundamental para cultivar una mente en calma.",
    "Hablar en público es fundamental para reconocer tu propio valor.",
    "La constancia se fortalece al soltar lo que no puedes controlar.",
    "La valentía es la clave para avanzar sin importar los obstáculos.",
    "La constancia es el reflejo de abrazar tu verdadera esencia.",
    "La calma te da la fuerza para vivir el momento presente.",
    "El éxito diario nos permite comunicar lo que sientes.",
    "El amor propio nace de la capacidad de transformar los nervios en energía.",
    "El esfuerzo te impulsa a mantenerse firme ante la adversidad.",
    "La calma te enseña a encontrar tu centro de paz.",
    "Tu confianza te conecta con abrazar tu verdadera esencia.",
    "El autocontrol significa poder proyectar seguridad al hablar.",
    "La resiliencia se fortalece al avanzar sin importar los obstáculos.",
    "El desarrollo propio es la clave para enfrentar tus miedos.",
    "La resiliencia es fundamental para expresar tus ideas con claridad.",
    "La perseverancia consiste en proyectar seguridad al hablar.",
    "El budismo nos enseña que es el arte de respirar hondo antes de actuar.",
    "La determinación consiste en expresar tus ideas con claridad.",
    "La tranquilidad mental te protege de respirar hondo antes de actuar.",
    "El autocontrol es el arte de vivir el momento presente.",
    "La armonía es fundamental para respirar hondo antes de actuar.",
    "El autocontrol se basa en vivir el momento presente.",
    "Tu voz se fortalece al ignorar las opiniones destructivas.",
    "Vencer los nervios se fortalece al proyectar seguridad al hablar.",
    "La valentía te da la fuerza para dejar atrás la ansiedad social.",
    "Hablar en público construye el camino para aprender de cada error.",
    "La sabiduría se fortalece al mantenerse firme ante la adversidad.",
    "El equilibrio es el primer paso para construir hábitos inquebrantables.",
    "La armonía te ayuda a soltar lo que no puedes controlar.",
    "La motivación transforma tu manera de comunicar lo que sientes.",
    "La calma transforma tu manera de mantener la mente enfocada.",
    "El budismo nos enseña que te enseña a confiar en tus capacidades.",
    "La asertividad es la clave para vivir el momento presente.",
    "La sabiduría se logra al comunicar lo que sientes.",
    "La asertividad es la clave para disfrutar del proceso de crecimiento.",
    "La asertividad consiste en soltar lo que no puedes controlar.",
    "Vencer los nervios abre la puerta a transformar los nervios en energía.",
    "El budismo nos enseña que rompe las barreras de dar un paso adelante cada día.",
    "La constancia consiste en encontrar tu centro de paz.",
    "Tu confianza te protege de comunicar lo que sientes.",
    "El desarrollo propio se nutre al reconocer tu propio valor.",
    "Hablar en público abre la puerta a confiar en tus capacidades.",
    "El esfuerzo te libera de vivir el momento presente.",
    "El crecimiento personal te enseña a aprender de cada error.",
    "La tranquilidad mental consiste en abrazar tu verdadera esencia.",
    "La calma nos permite aprender de cada error.",
    "La perseverancia comienza cuando decides respirar hondo antes de actuar.",
    "El enfoque te da la fuerza para mantenerse firme ante la adversidad.",
    "El éxito diario te ayuda a superar la necesidad de aprobación.",
    "El coraje rompe las barreras de aprender de cada error.",
    "La sabiduría te libera de transformar los nervios en energía.",
    "El desarrollo propio te ayuda a enfrentar tus miedos.",
    "Superar la timidez requiere que aprendas a aprender de cada error.",
    "El miedo al rechazo se basa en enfrentar tus miedos.",
    "El crecimiento personal se basa en soltar lo que no puedes controlar.",
    "Vencer los nervios se fortalece al creer en el poder de tus palabras.",
    "El esfuerzo se logra al encontrar tu centro de paz.",
    "La paz interior te ayuda a conectar auténticamente con los demás.",
    "La constancia te impulsa a creer en el poder de tus palabras.",
    "Vencer los nervios te enseña a expresar tus ideas con claridad.",
    "La constancia es la clave para ignorar las opiniones destructivas.",
    "La determinación es el primer paso para construir hábitos inquebrantables.",
    "La serenidad se fortalece al ignorar las opiniones destructivas.",
    "La constancia es fundamental para creer en el poder de tus palabras.",
    "La determinación es el primer paso para respirar hondo antes de actuar.",
    "El budismo nos enseña que te da la fuerza para dejar atrás la ansiedad social.",
    "La paz interior abre la puerta a expresar tus ideas con claridad.",
    "El éxito diario se basa en proyectar seguridad al hablar.",
    "La calma te guía hacia avanzar sin importar los obstáculos.",
    "El crecimiento personal te conecta con vivir el momento presente.",
    "La serenidad abre la puerta a vivir el momento presente.",
    "La sabiduría te enseña a dar un paso adelante cada día.",
    "La valentía te enseña a vivir el momento presente.",
    "La perseverancia abre la puerta a ignorar las opiniones destructivas.",
    "La paz interior es el arte de transformar los nervios en energía.",
    "La verdadera disciplina requiere que aprendas a mantenerse firme ante la adversidad.",
    "La atención plena se basa en comunicar lo que sientes.",
    "La sabiduría significa poder proyectar seguridad al hablar.",
    "La valentía es el arte de soltar lo que no puedes controlar.",
    "La armonía comienza cuando decides proyectar seguridad al hablar.",
    "El equilibrio nos permite superar la necesidad de aprobación.",
    "El pensamiento positivo significa poder superar la necesidad de aprobación.",
    "La determinación se nutre al avanzar sin importar los obstáculos.",
    "El éxito diario consiste en vivir el momento presente.",
    "El crecimiento personal es fundamental para dejar atrás la ansiedad social.",
    "Vencer los nervios es el arte de cultivar una mente en calma.",
    "La calma es fundamental para dar un paso adelante cada día.",
    "La calma consiste en abrazar tu verdadera esencia.",
    "La tranquilidad mental te enseña a transformar los nervios en energía.",
    "El coraje te conecta con reconocer tu propio valor.",
    "El enfoque consiste en creer en el poder de tus palabras.",
    "La perseverancia te guía hacia superar la necesidad de aprobación.",
    "El pensamiento positivo significa poder dejar atrás la ansiedad social.",
    "La determinación te enseña a reconocer tu propio valor.",
    "La valentía se fortalece al expresar tus ideas con claridad.",
    "El crecimiento personal nos permite ignorar las opiniones destructivas.",
    "El budismo nos enseña que te da la fuerza para soltar lo que no puedes controlar.",
    "El crecimiento personal consiste en mantener la mente enfocada.",
    "La atención plena es el arte de enfrentar tus miedos.",
    "La resiliencia es el reflejo de dejar atrás la ansiedad social.",
    "Tu voz te enseña a dejar atrás la ansiedad social.",
    "La calma es fundamental para enfrentar tus miedos.",
    "El miedo al rechazo te enseña a reconocer tu propio valor.",
    "El pensamiento positivo es el reflejo de mantener la mente enfocada.",
    "El autocontrol te libera de aprender de cada error.",
    "El amor propio nace de la capacidad de dar un paso adelante cada día.",
    "La calma rompe las barreras de aprender de cada error.",
    "El coraje te conecta con disfrutar del proceso de crecimiento.",
    "La serenidad transforma tu manera de ignorar las opiniones destructivas.",
    "El éxito diario te enseña a mantener la mente enfocada.",
    "Tu voz requiere que aprendas a confiar en tus capacidades.",
    "La resiliencia te impulsa a confiar en tus capacidades.",
    "La asertividad transforma tu manera de encontrar tu centro de paz.",
    "El pensamiento positivo nos permite superar la necesidad de aprobación.",
    "La motivación ilumina el sendero hacia abrazar tu verdadera esencia.",
    "La perseverancia se basa en aprender de cada error.",
    "La tranquilidad mental te protege de abrazar tu verdadera esencia.",
    "El autoconocimiento te da la fuerza para aprender de cada error.",
    "El coraje te enseña a reconocer tu propio valor.",
    "La motivación te guía hacia expresar tus ideas con claridad.",
    "El autocontrol comienza cuando decides expresar tus ideas con claridad.",
    "La resiliencia abre la puerta a soltar lo que no puedes controlar.",
    "La perseverancia es la clave para comunicar lo que sientes.",
    "Tu confianza significa poder comunicar lo que sientes.",
    "La serenidad construye el camino para disfrutar del proceso de crecimiento.",
  ];

  static String getDailyQuote() {
    final now = DateTime.now();
    final dayOfYear = int.parse(now.difference(DateTime(now.year, 1, 1)).inDays.toString()) + 1;
    final index = (dayOfYear - 1) % quotes.length;
    return quotes[index];
  }
}
